// js/api.js — every database query the app makes (full docs: ../ARCHITECTURE.md §2, §3)
//
// One small named method per operation, grouped by table. RULE: page code never
// calls sbFetch directly — add a method here instead, so the whole data surface
// is scannable in one file. All methods return promises of parsed JSON rows.

const API = {
  // ---- projects ----
  getProjects() {
    return sbFetch("projects?select=*&order=created_at.asc");
  },
  getProject(id) {
    return sbFetch(`projects?id=eq.${id}&select=*`).then((r) => r[0] || null);
  },
  getSubProjects(parentId) {
    return sbFetch(`projects?parent_project_id=eq.${parentId}&archived=eq.false&select=*&order=name.asc`);
  },
  createProject(fields) {
    return sbFetch("projects", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateProject(id, fields) {
    return sbFetch(`projects?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  // Live-inheriting children of a parent (incl. archived ones — their tasks
  // must never be orphaned by a parent status edit). Requires sql/12;
  // callers guard on the inherit_statuses column existing.
  getInheritingChildren(parentId) {
    return sbFetch(
      `projects?parent_project_id=eq.${parentId}&inherit_statuses=eq.true&select=id,name,statuses`
    );
  },

  // ---- tasks ----
  getTasks(projectId) {
    return sbFetch(`tasks?project_id=eq.${projectId}&select=*`);
  },
  // Lightweight fetch for dashboard counts (all projects at once)
  getTaskSummaries() {
    return sbFetch("tasks?select=project_id,due_date");
  },
  // Every task across all active projects, with project info embedded (All Tasks view).
  // projects(*) rather than a column list so new project columns (e.g.
  // parent_project_id) flow through without breaking pre-migration.
  getAllTasks() {
    return sbFetch(
      "tasks?select=*,projects!inner(*)&projects.archived=eq.false" +
        "&order=due_date.asc.nullslast,created_at.asc"
    );
  },
  createTask(fields) {
    return sbFetch("tasks", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateTask(id, fields) {
    return sbFetch(`tasks?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteTask(id) {
    return sbFetch(`tasks?id=eq.${id}`, { method: "DELETE" });
  },
  // Task id/status/project across a set of projects — feeds the transition
  // mapping step when status columns change.
  getTasksByProjects(projectIds) {
    return sbFetch(`tasks?project_id=in.(${projectIds.join(",")})&select=id,project_id,status`);
  },
  // Bulk transition-mapping move. Each updated task fires the webhook and
  // status_changed automation triggers once (server-side) — that's correct:
  // the tasks really did change status.
  moveTasksByStatus(projectIds, fromStatus, toStatus) {
    return sbFetch(
      `tasks?project_id=in.(${projectIds.join(",")})&status=eq.${encodeURIComponent(fromStatus)}`,
      { method: "PATCH", body: { status: toStatus } }
    );
  },
  memberHasTasks(memberId) {
    return sbFetch(`tasks?assignee_id=eq.${memberId}&select=id&limit=1`).then((r) => r.length > 0);
  },

  // ---- webhooks (outgoing Zapier integrations) ----
  getWebhooks() {
    return sbFetch("webhooks?select=*&order=created_at.asc");
  },
  createWebhook(fields) {
    return sbFetch("webhooks", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateWebhook(id, fields) {
    return sbFetch(`webhooks?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteWebhook(id) {
    return sbFetch(`webhooks?id=eq.${id}`, { method: "DELETE" });
  },
  sendTestWebhook(id) {
    return sbFetch("rpc/send_test_webhook", { method: "POST", body: { webhook_id: id } });
  },

  // ---- automations (per-project rules: trigger -> action) ----
  getAutomations(projectId) {
    return sbFetch(`automations?project_id=eq.${projectId}&select=*&order=created_at.asc`);
  },
  createAutomation(fields) {
    return sbFetch("automations", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateAutomation(id, fields) {
    return sbFetch(`automations?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteAutomation(id) {
    return sbFetch(`automations?id=eq.${id}`, { method: "DELETE" });
  },
  sendTestAutomation(id) {
    return sbFetch("rpc/send_test_automation", { method: "POST", body: { automation_id: id } });
  },

  // ---- API keys (native inbound API — Sheets/scripts create tasks directly) ----
  getApiKeys() {
    return sbFetch("api_keys?select=*&order=created_at.asc");
  },
  createApiKey(fields) {
    // key column is generated by the database default
    return sbFetch("api_keys", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateApiKey(id, fields) {
    return sbFetch(`api_keys?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteApiKey(id) {
    return sbFetch(`api_keys?id=eq.${id}`, { method: "DELETE" });
  },

  // ---- team members ----
  getMembers() {
    return sbFetch("team_members?select=*&order=name.asc");
  },
  createMember(fields) {
    return sbFetch("team_members", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateMember(id, fields) {
    return sbFetch(`team_members?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteMember(id) {
    return sbFetch(`team_members?id=eq.${id}`, { method: "DELETE" });
  },

  // ---- notifications (inbox) ----
  getNotifications(memberId) {
    return sbFetch(
      `notifications?member_id=eq.${memberId}&select=*,actor:actor_id(name),projects(name)` +
        "&order=created_at.desc&limit=50"
    );
  },
  getUnreadCount(memberId) {
    return sbFetch(`notifications?member_id=eq.${memberId}&read=eq.false&select=id`).then(
      (r) => r.length
    );
  },
  setRead(id, read) {
    return sbFetch(`notifications?id=eq.${id}`, { method: "PATCH", body: { read } });
  },
  markAllRead(memberId) {
    return sbFetch(`notifications?member_id=eq.${memberId}&read=eq.false`, {
      method: "PATCH",
      body: { read: true },
    });
  },
  // rows: [{member_id, kind, actor_id, task_id, project_id, message}]
  notify(rows) {
    if (!rows.length) return Promise.resolve([]);
    return sbFetch("notifications", { method: "POST", body: rows });
  },
  // Only this member's tasks, filtered server-side — the inbox scales with
  // the user's workload, not the whole org's task count
  getMyTasks(memberId) {
    return sbFetch(
      `tasks?assignee_id=eq.${memberId}` +
        // projects(*) so inherit_statuses flows through pre/post-migration;
        // the parent embed feeds UI.effectiveStatuses for inheriting subs.
        "&select=*,projects!inner(*,parent:parent_project_id(statuses))&projects.archived=eq.false" +
        "&order=due_date.asc.nullslast,created_at.asc&limit=300"
    );
  },

  // ---- HR roles (roles summary card on HR project boards) ----
  getHrRoles(projectId) {
    return sbFetch(`hr_roles?project_id=eq.${projectId}&select=*&order=sort_order.asc`);
  },
  createHrRole(fields) {
    return sbFetch("hr_roles", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateHrRole(id, fields) {
    return sbFetch(`hr_roles?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteHrRole(id) {
    return sbFetch(`hr_roles?id=eq.${id}`, { method: "DELETE" });
  },

  // ---- HR SLA rules (per-project deadline config) ----
  getSlaRules(projectId) {
    return sbFetch(`hr_sla_rules?project_id=eq.${projectId}&select=*&order=created_at.asc`);
  },
  createSlaRule(fields) {
    return sbFetch("hr_sla_rules", { method: "POST", body: fields }).then((r) => r[0]);
  },
  updateSlaRule(id, fields) {
    return sbFetch(`hr_sla_rules?id=eq.${id}`, { method: "PATCH", body: fields }).then((r) => r[0]);
  },
  deleteSlaRule(id) {
    return sbFetch(`hr_sla_rules?id=eq.${id}`, { method: "DELETE" });
  },

  // ---- tags (central registry feeding all tag dropdowns) ----
  getTags() {
    return sbFetch("tags?select=*&order=name.asc");
  },
  createTag(name) {
    return sbFetch("tags", { method: "POST", body: { name } }).then((r) => r[0]);
  },
  deleteTag(id) {
    return sbFetch(`tags?id=eq.${id}`, { method: "DELETE" });
  },

  // ---- project access (external users) ----
  getProjectAccess(memberId) {
    return sbFetch(`project_members?member_id=eq.${memberId}&select=project_id`);
  },
  getAllProjectAccess() {
    return sbFetch("project_members?select=member_id,project_id");
  },
  addProjectAccess(memberId, projectId) {
    return sbFetch("project_members", {
      method: "POST",
      body: { member_id: memberId, project_id: projectId },
    });
  },
  removeProjectAccess(memberId, projectId) {
    return sbFetch(`project_members?member_id=eq.${memberId}&project_id=eq.${projectId}`, {
      method: "DELETE",
    });
  },
};
